Repository rsyslog/rsyslog-doc, pull requests merged in 2018-03, with the labels that each got.

#593 omelasticsearch: rewrite documentation
  source/configuration/modules/omelasticsearch.rst
Labels: enhancement

#601 Fix SysSock.Name parameter type
  source/configuration/modules/imuxsock.rst
Labels: bug

#586 imudp: rewrite documentation
  source/configuration/modules/imudp.rst
Labels: enhancement

#628 imuxsock: Update label refs to use module prefix
  source/configuration/modules/imuxsock.rst
Labels: bug

#591 include(): Add section headers, formatting tweaks
  source/rainerscript/include.rst
Labels: enhancement, waitingOnReview

#612 Render sysklogd examples as <pre> or the like
  source/configuration/sysklogd_format.rst
Labels: enhancement

#629 Clarify how action.resumeInterval increases over time
  source/configuration/actions.rst
Labels: enhancement, waitingOnReview

#619 queue parameters: State need for queue.filename
  source/rainerscript/queue_parameters.rst
Labels: waitingOnReview

#635 "basic" format doc tweaks: formatting, headers
  source/configuration/sysklogd_format.rst
Labels: waitingOnReview

#633 add documentation for the change to module and built-in functions
  source/rainerscript/functions.rst
Labels: new feature, waitingOnResponse

#624 Update references to support resources
  source/includes/footer.inc.rst
  source/includes/substitution_definitions.inc.rst
Labels: waitingOnResponse

#614 Fix typos in config.enabled parameter name
  source/rainerscript/configuration_objects.rst
Labels: bug
