Repository rsyslog/rsyslog-doc, pull requests merged in 2018-05, with the labels that each got.

#650 Document imklog ratelimit
  source/configuration/modules/imklog.rst
Labels: enhancement, waitingOnPR, waitingOnReview

#660 describe new global parameter "internal.developeronly.options"
  source/rainerscript/global.rst
Labels: waitingOnPR

#656 imrelp: add doc for parameter oversizeMode
  source/configuration/modules/imrelp.rst
Labels: enhancement, waitingOnPR, waitingOnReview

#657 omprog: rewrite documentation
  source/configuration/modules/omprog.rst
Labels: enhancement, waitingOnResponse
