Repository rsyslog/rsyslog-doc, pull requests merged in 2018-04, with the labels that each got.

#637 rainerscript: function documentation split up
  source/rainerscript/functions.rst
  source/rainerscript/functions/idx_built-in_functions.rst
  source/rainerscript/functions/idx_module_functions.rst
  source/rainerscript/functions/index.rst
  source/rainerscript/functions/mo-http_request.rst
  source/rainerscript/functions/rs-cnum.rst
  source/rainerscript/functions/rs-cstr.rst
  source/rainerscript/functions/rs-dyn_inc.rst
  source/rainerscript/functions/rs-exec_template.rst
  source/rainerscript/functions/rs-field.rst
  source/rainerscript/functions/rs-format_time.rst
  source/rainerscript/functions/rs-getenv.rst
  source/rainerscript/functions/rs-int2hex.rst
  source/rainerscript/functions/rs-ipv4convert.rst
  source/rainerscript/functions/rs-is_time.rst
  source/rainerscript/functions/rs-lookup.rst
  source/rainerscript/functions/rs-parse_json.rst
  source/rainerscript/functions/rs-parse_time.rst
  source/rainerscript/functions/rs-previous_action_suspended.rst
  source/rainerscript/functions/rs-prifilt.rst
  source/rainerscript/functions/rs-random.rst
  source/rainerscript/functions/rs-re_extract.rst
  source/rainerscript/functions/rs-re_match.rst
  source/rainerscript/functions/rs-replace.rst
  source/rainerscript/functions/rs-script_error.rst
  source/rainerscript/functions/rs-strlen.rst
  source/rainerscript/functions/rs-substring.rst
  source/rainerscript/functions/rs-tolower.rst
  source/rainerscript/functions/rs-trim.rst
  source/rainerscript/functions/rs-wrap.rst
  source/rainerscript/index.rst
Labels: DO-NOT-MERGE_work-in-progress

#641 rainerscript functions: add information
  source/rainerscript/functions/idx_built-in_functions.rst
  source/rainerscript/functions/rs-int2hex.rst
  source/rainerscript/functions/rs-re_extract.rst
  source/rainerscript/functions/rs-re_match.rst
  source/rainerscript/functions/rs-substring.rst
Labels: enhancement, waitingOnReview

#644 global: remove invalid permitSlash parameter
  source/rainerscript/global.rst
Labels: bug, waitingOnReview

#643 Add documentation for the new SocketBacklog parameter of the imptcp module
  source/configuration/modules/imptcp.rst
Labels: enhancement

#642 README: remove forum ref, add Stack Exchange refs
  README.md
Labels: waitingOnReview

#647 mmkubernetes doc updates to go with recent fixes
  source/configuration/modules/mmkubernetes.rst
Labels: waitingOnPR, waitingOnReview

#648 fix samples in sysklogd format description
  source/configuration/sysklogd_format.rst
Labels: bug

#649 Add descriptions for address and ipfreebind options in omfwd
  source/configuration/modules/omfwd.rst
Labels: waitingOnPR, waitingOnReview

#659 omrelp: rewrite documentation
  source/configuration/modules/omrelp.rst
Labels: enhancement
