Repository rsyslog/rsyslog-doc, pull requests merged in 2018-02, with the labels that each got.

#509 omrelp: Add RebindInterval parameter
  source/configuration/modules/omrelp.rst
Labels: waitingOnResponse

#552 Add missing complement to dev build logic
  source/conf.py
Labels: bug, build process

#553 fix docker container: contained rsyslog.com site theme
  tools/buildenv/Dockerfile
Labels: bug

#567 CONTRIB: add info on how to find PR preview html link
  CONTRIBUTING.md
Labels: build process, enhancement

#577 fix invalid parameter name
  source/rainerscript/global.rst
Labels: bug

#579 Add doc-specific label refs for stats section
  source/configuration/modules/impstats.rst
  source/configuration/modules/imptcp.rst
  source/configuration/modules/imrelp.rst
Labels: bug

#578 Add back project prefix to dev build string for epub builds
  source/conf.py
Labels: bug, build process

#589 Fix reference to ActionForwardDefaultTemplate in omfwd.rst
  source/configuration/modules/omfwd.rst
Labels: bug

#588 omamqp1: rewrite documentation
  source/configuration/modules/omamqp1.rst
Labels: enhancement

#587 imtcp: rewrite documentation
  source/configuration/modules/imtcp.rst
Labels: DO-NOT-MERGE_work-in-progress, enhancement
